### ISSUE TITLE
C++ 프로젝트 적용 문의

### ISSUE THREAD

**Issue by choi-inkyun** [naver/cover-checker#13]
안녕하세요 : )
다름이 아니라, 저희 프로젝트는 C++로 되어 있는데요.
아래 이슈도 그렇고, Java 프로젝트만 분석을 지원하는 것 같은데 맞는지 궁금합니다.
처음에는 이에 대해서 잘 모르고 연동을 시작해서 우선 진행해보았는데요.

아래와 같이 분석 결과가 항상 0/0 100으로 나오고 PR Comment도 동일한데, C++을 지원하지 않기 때문에 그런 것인지, 아니면 다른 부분을 살펴볼 수 있을지 궁금합니다.
만약 C++ 을 지원하지 않아서 그런 것이라면, 혹시 C++ 대해서도 분석을 지원하실 계획이 있으신지 궁금합니다.

```
+  java -jar /home1/irteamsu/CI/coverchecker-1.3.3-jar-with-dependencies.jar -c /home1/irteamsu/jenkins_home/workspace/nmss-pr-pipeline/cobertura-coverage.xml -g <TOKEN> -r videocell-tech/NMSS -t 5 -u oss.navercorp.com -p 1445 -type cobertura
19:02:14.445 [main] INFO  [CoverChecker.java:59] Check new line of code coverage by XmlCoverageReportParser
19:02:14.453 [main] INFO  [CoverChecker.java:63] read diff by GithubRawDiffReader
19:02:14.462 [ForkJoinPool.commonPool-worker-50] INFO  [GithubDiffManager.java:40] get diff videocell-tech/NMSS/1445
19:02:14.633 [ForkJoinPool.commonPool-worker-50] INFO  [GithubRawDiffReader.java:58] get file MediaServer/Common/Utils/VttToTtml.cpp
19:02:14.637 [ForkJoinPool.commonPool-worker-50] INFO  [DiffMapper.java:53] parse diff / Optional[MediaServer/Common/Utils/VttToTtml.cpp]
19:02:14.647 [ForkJoinPool.commonPool-worker-50] INFO  [GithubRawDiffReader.java:58] get file MediaServer/Common/Utils/VttToTtml.h
19:02:14.648 [ForkJoinPool.commonPool-worker-50] INFO  [DiffMapper.java:53] parse diff / Optional[MediaServer/Common/Utils/VttToTtml.h]
19:02:14.670 [main] INFO  [ConsoleReporter.java:29] coverage check result
19:02:14.671 [main] INFO  [ConsoleReporter.java:31] 0/0 100
19:02:15.670 [main] INFO  [CoverChecker.java:71] check result pass 
```

위와 같이 분석이 안되서 다른 방법으로 -d 하고 -dt file 옵션을 사용해 봤는데요.
이 경우 아래와 같이 Exception이 발생 하였습니다.

```
+ java -jar /home1/irteamsu/CI/coverchecker-1.3.3-jar-with-dependencies.jar -c /home1/irteamsu/jenkins_home/workspace/nmss-pr-pipeline/cobertura-coverage.xml -d /home1/irteamsu/jenkins_home/workspace/nmss-schedule-pipeline/cobertura-coverage.xml -dt file -g <TOKEN> -r videocell-tech/NMSS -t 1 -u oss.navercorp.com -p 1448 -type cobertura

<생략>
18:20:21.864 [main] INFO  [ConsoleReporter.java:29] coverage check result
18:20:21.866 [main] ERROR [ConsoleReporter.java:37] result error occurred
java.lang.NullPointerException: null
        at com.naver.nid.cover.checker.NewCoverageChecker.lambda$check$0(NewCoverageChecker.java:49)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.naver.nid.cover.checker.NewCoverageChecker.check(NewCoverageChecker.java:54)
        at com.naver.nid.cover.CoverChecker.check(CoverChecker.java:68)
        at com.naver.nid.cover.CoverChecker.main(CoverChecker.java:97)

```

지금 팀에 Java 프로젝트가 없고 익숙하지 않다보니 Java는 현재 환경에서 정상적으로 동작하는지 테스트를 해보지 못한 부분이 아쉽긴 한데요. 시간 내서 한번 테스트를 진행해보도록 하겠습니다.

감사합니다.

**Comment by choi-inkyun** [comment]
위에 분석이 안되는 문제는 https://github.com/naver/cover-checker/blob/master/src/main/java/com/naver/nid/cover/checker/NewCoverageChecker.java#L50 코드를 삭제하고 빌드해서 사용해보니 저희 코드에서도 우선 결과가 잘 나오는 것 같습니다. 
감사합니다.

**Comment by ksmail13** [comment]
안녕하세요. 말씀해주신 부분은 다음 패치 때 수정될 예정입니다.
