### ISSUE TITLE
커버리지 결과에서 hit 수가 많을 경우 Exception이 발생하는 문제

### ISSUE THREAD

**Issue by choi-inkyun** [naver/cover-checker#25]
안녕하세요.

이번에 cover-checker 1.4.0 에서 아래와 같은 Comment 와 Exception이 발생 하였습니다.
![image](https://user-images.githubusercontent.com/2978067/101317265-82c87f00-38a1-11eb-8e71-e742b9a419a7.png)

```
15:12:26.367 [main] INFO  (CoverChecker.java:47) Check new line of code coverage by XmlCoverageReportParser
15:12:26.376 [main] INFO  (CoverChecker.java:53) read diff by GithubDiffReader
15:12:26.381 [ForkJoinPool.commonPool-worker-87] INFO  (GithubDiffManager.java:40) get diff video-tech1/MediaComparator/135
15:12:26.410 [main] INFO  (ConsoleReporter.java:28) coverage check result
15:12:26.412 [main] ERROR (ConsoleReporter.java:36) result error occurred
java.util.concurrent.CompletionException: java.lang.NumberFormatException: For input string: "2338181480"
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NumberFormatException: For input string: "2338181480"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.naver.nid.cover.cobertura.CoberturaCoverageReportHandler.getCoverageStatus(CoberturaCoverageReportHandler.java:94)
	at com.naver.nid.cover.cobertura.CoberturaCoverageReportHandler.initLine(CoberturaCoverageReportHandler.java:80)
	at com.naver.nid.cover.cobertura.CoberturaCoverageReportHandler.startElement(CoberturaCoverageReportHandler.java:60)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:731)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:330)
	at com.naver.nid.cover.parser.coverage.XmlCoverageReportParser.parse(XmlCoverageReportParser.java:50)
	at com.naver.nid.cover.parser.coverage.CoverageReportParser.parse(CoverageReportParser.java:31)
	at com.naver.nid.cover.CoverChecker.lambda$null$5(CoverChecker.java:74)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 6 common frames omitted
```

커버리지 xml 을 확인해보니, 특정 라인들의 hit 수가 20억번 이상과 같이 매우 큰 값이 되어 발생하는 것 같습니다.

```
<class branch-rate="0.763157894737" complexity="0.0" filename="src/analyzer/quality/PsnrCalculator.cpp" line-rate="0.931034482759" name="PsnrCalculator_cpp">
<methods/>
<lines>
<line branch="false" hits="23231" number="7"/>
<line branch="true" condition-coverage="50% (2/4)" hits="23231" number="8">
<conditions>
<condition coverage="50%" number="0" type="jump"/>
</conditions>
</line>
<line branch="true" condition-coverage="50% (2/4)" hits="46462" number="9">
<conditions>
<condition coverage="50%" number="0" type="jump"/>
</conditions>
</line>
<line branch="true" condition-coverage="100% (2/2)" hits="6745431" number="11">
<conditions>
<condition coverage="100%" number="0" type="jump"/>
</conditions>
</line>
<line branch="true" condition-coverage="100% (2/2)" hits="2338181480" number="12">
<conditions>
<condition coverage="100%" number="0" type="jump"/>
</conditions>
</line>
<line branch="true" condition-coverage="50% (1/2)" hits="2331459280" number="13">
<conditions>
<condition coverage="50%" number="0" type="jump"/>
</conditions>
</line>
<line branch="true" condition-coverage="50% (1/2)" hits="2331459280" number="14">
<conditions>
<condition coverage="50%" number="0" type="jump"/>
</conditions>
</line>
<line branch="true" condition-coverage="100% (2/2)" hits="9325837120" number="15">
<conditions>
<condition coverage="100%" number="0" type="jump"/>
</conditions>
</line>
<line branch="true" condition-coverage="50% (1/2)" hits="6994377840" number="16">
<conditions>
<condition coverage="50%" number="0" type="jump"/>
</conditions>
</line>
<line branch="true" condition-coverage="50% (1/2)" hits="6994377840" number="17">
<conditions>
<condition coverage="50%" number="0" type="jump"/>
</conditions>
</line>
```

우선 해당 파일을 커버리지에서 제외 처리하거나, 유닛 테스트를 수정해서 좀 덜 호출되도록 하는 방향으로 진행 중입니다.

감사합니다^^

**Comment by ksmail13** [comment]
항상 제보 감사드립니다.

해당 라인의 cover 여부를 체크하기 위한 내부 변수의 hits 값을 체크하기 위해 integer 값으로 확인 중인데
값이 넘어가 문제가 되는 것 같습니다.

수정해서 업데이트 하겠습니다.
