### ISSUE TITLE
Error Bad credentials (401) when Pull Request is from a fork repository

### ISSUE THREAD

**Issue by ideoma** [naver/cover-checker#36]
I noticed that the cover-checker does not work when it is set for a pull request from a forked repository. The failure is 

```
Exception in thread "main" java.lang.IllegalStateException: org.eclipse.egit.github.core.client.RequestException: Bad credentials (401)
	at com.naver.nid.cover.github.manager.GithubPullRequestManager.<init>(GithubPullRequestManager.java:52)
	at com.naver.nid.cover.github.manager.GithubPullRequestManager.<init>(GithubPullRequestManager.java:38)
	at com.naver.nid.cover.util.ObjectFactory.getPrManager(ObjectFactory.java:71)
	at com.naver.nid.cover.util.ObjectFactory.getDiffReader(ObjectFactory.java:46)
	at com.naver.nid.cover.Launcher.main(Launcher.java:15)
Caused by: org.eclipse.egit.github.core.client.RequestException: Bad credentials (401)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:606)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:799)
	at org.eclipse.egit.github.core.service.PullRequestService.getPullRequest(PullRequestService.java:115)
	at com.naver.nid.cover.github.manager.GithubPullRequestManager.<init>(GithubPullRequestManager.java:50)
	... 4 more
```

Full log is here 

https://dev.azure.com/questdb/questdb/_build/results?buildId=1357&view=logs&j=55742375-e338-54e5-b4e4-08a24a4c7b3d&t=8306d4b1-7a02-5def-a13e-6cf8bb46e3ff

This happens in all cross repo PRs:

- https://github.com/questdb/questdb/pull/1093
- https://github.com/questdb/questdb/pull/905

and does not happen with PRs when branch is in the same repo as the target:

https://github.com/questdb/questdb/pulls?q=is%3Apr+is%3Aclosed

even though github token is the same in the Azure pipeline.

Would be good to have a hint of how to avoid 401 error

**Comment by ideoma** [comment]
Apparently this is nothing to do with the cover-checker but Azure security considerations for PRs from forks

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#important-security-considerations
